[project]
name = "robyn-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "msgspec>=0.21.1",
    "piccolo>=1.36.0",
    "robyn>=0.88.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "ty>=0.0.64",
]
test = [
    "pytest>=9.1.1",
    "requests>=2.34.2",
]
