name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
    - 'javascript/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'javascript/**'

permissions:
  contents: read

jobs:
  quality-and-test:
    name: Lint, Format & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ 'builtin', 'express' ]
        node-version: [ '20.x', '22.x' ]

    defaults:
      run:
        working-directory: ./javascript/nodejs-example/${{ matrix.project }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: javascript/nodejs-example/${{ matrix.project }}/package-lock.json

      - name: Clean Install Dependencies
        run: npm ci

      # - name: Code Formatting Check (Prettier)
      #   run: npx prettier --check . --ignore-path ./.prettierignore

      # - name: Linting & Static Analysis (ESLint)
      #   run: npx eslint .

      # - name: Run Test Suite
      #   run: npm test --if-present
